import { StyleSheet } from 'react-native';

export const stopwatchesStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  historyButton: {
    backgroundColor: '#27ae60',
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginBottom: 5,
  },
  historyButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: '#253494',
    borderRadius: 20,
    padding: 30,
    marginBottom: 20,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 5,
  },
  timerText: {
    fontSize: 70,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 30,
    width: '100%',
  },
  button: {
    backgroundColor: '#253494',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    height: 60,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: '#253494',
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    width: '90%',
    color: '#000',
    backgroundColor: '#fff',
    fontSize: 18,
    paddingHorizontal: 10,
    elevation: 3,
  },
  picker: {
    borderWidth: 1,
    borderColor: '#253494',
    borderRadius: 10,
    marginBottom: 20,
    backgroundColor: '#fff',
    elevation: 3,
    width: '90%',
  },
  saveButton: {
    backgroundColor: '#253494',
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginBottom: 5,
  },
});
